import { Bank } from "../../utility/types";

export const supportedBanks: Bank[] = [
  {
    id: "1",
    name: "Access Bank",
    short_code: "044",
    code: "000014",
    img_url: require("../../assets/banks/access-bank.png"),
  },
  {
    id: "2",
    name: "Citibank",
    short_code: "023",
    code: "",
    img_url: require("../../assets/banks/citibank-nigeria.png"),
  },
  {
    id: "3",
    name: "Carbon",
    short_code: "565",
    code: "100026",
    img_url: require("../../assets/banks/default-image.png"),
  },
  {
    id: "4",
    name: "Diamond Bank",
    short_code: "063",
    code: "000014",
    img_url: require("../../assets/banks/access-bank.png"),
  },
  {
    id: "5",
    name: "Ecobank Nigeria",
    short_code: "050",
    code: "100008",
    img_url: require("../../assets/banks/ecobank-nigeria.png"),
  },
  {
    id: "6",
    name: "Fidelity Bank Nigeria",
    short_code: "070",
    code: "000007",
    img_url: require("../../assets/banks/fidelity-bank.png"),
  },
  {
    id: "7",
    name: "First Bank of Nigeria",
    short_code: "011",
    code: "000016",
    img_url: require("../../assets/banks/first-bank-of-nigeria.png"),
  },
  {
    id: "8",
    name: "First City Monument Bank",
    short_code: "214",
    code: "",
    img_url: require("../../assets/banks/first-city-monument-bank.png"),
  },
  {
    id: "9",
    name: "Guaranty Trust Bank",
    short_code: "058",
    code: "000013",
    img_url: require("../../assets/banks/guaranty-trust-bank.png"),
  },
  {
    id: "10",
    name: "Heritage Bank Plc",
    short_code: "030",
    code: "000020",
    img_url: require("../../assets/banks/heritage-bank.png"),
  },
  {
    id: "11",
    name: "Jaiz Bank",
    short_code: "301",
    code: "000006",
    img_url: require("../../assets/banks/default-image.png"),
  },
  {
    id: "12",
    name: "Keystone Bank Limited",
    short_code: "082",
    code: "000002",
    img_url: require("../../assets/banks/keystone-bank.png"),
  },
  {
    id: "13",
    name: "Kuda Bank",
    short_code: "082", //seb kuda short code
    code: "50211",
    img_url: require("../../assets/banks/kuda-bank.png"),
  },
  {
    id: "14",
    name: "Opay",
    short_code: "100004",
    code: "100004",
    img_url: require("../../assets/banks/default-image.png"),
  },
  {
    id: "15",
    name: "PalmPay",
    short_code: "999991",
    code: "100033",
    img_url: require("../../assets/banks/default-image.png"),
  },
  {
    id: "16",
    name: "Providus Bank Plc",
    short_code: "101",
    code: "000023",
    img_url: require("../../assets/banks/default-image.png"),
  },
  {
    id: "17",
    name: "Polaris Bank",
    short_code: "076",
    code: "000008",
    img_url: require("../../assets/banks/polaris-bank.png"),
  },
  {
    id: "18",
    name: "Stanbic IBTC Bank Nigeria Limited",
    short_code: "221",
    code: "100007",
    img_url: require("../../assets/banks/stanbic-ibtc-bank.png"),
  },
  {
    id: "19",
    name: "Standard Chartered Bank",
    short_code: "068",
    code: "000021",
    img_url: require("../../assets/banks/standard-chartered-bank.png"),
  },
  {
    id: "20",
    name: "Sterling Bank",
    short_code: "232",
    code: "000001",
    img_url: require("../../assets/banks/sterling-bank.png"),
  },
  {
    id: "21",
    name: "Suntrust Bank Nigeria Limited",
    short_code: "100",
    code: "000022",
    img_url: require("../../assets/banks/default-image.png"),
  },
  {
    id: "22",
    name: "Union Bank of Nigeria",
    short_code: "032",
    code: "000018",
    img_url: require("../../assets/banks/union-bank-of-nigeria.png"),
  },
  {
    id: "23",
    name: "United Bank for Africa",
    short_code: "033",
    code: "000004",
    img_url: require("../../assets/banks/united-bank-for-africa.png"),
  },
  {
    id: "24",
    name: "Unity Bank Plc",
    short_code: "215",
    code: "000011",
    img_url: require("../../assets/banks/default-image.png"),
  },
  {
    id: "25",
    name: "Wema Bank",
    short_code: "035",
    code: "",
    img_url: require("../../assets/banks/wema-bank.png"),
  },
  {
    id: "26",
    name: "Zenith Bank",
    short_code: "057",
    code: "000015",
    img_url: require("../../assets/banks/zenith-bank.png"),
  },
];
